services:
  webserver:
    image: nginx:alpine
    depends_on:
      - php-fpm
    container_name: webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  php-fpm:
    build: docker/php-fpm
    container_name: php
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    environment:
        - PHP_MEMORY_LIMIT=4G
    depends_on:
        - mariadb

  redis:
    image: redis:alpine
    container_name: cache
    volumes:
      - ./docker/data/redis:/data
    ports:
      - 6379:6379

  mariadb:
    image: mariadb:11.0
    container_name: database
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/data/mysql:/var/lib/mysql:Z
      - ./database/config:/etc/mysql/mariadb.conf.d:99-mariadb-tweaks.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
